/*
 * MainGUI.java
 *
 * Created on 27. marts 2007, 15:44
 */

package iso2avi;

import java.io.File;
import java.util.Vector;
import javax.swing.JFileChooser;

/**
 *
 * @author  Rolf
 */
public class MainGUI extends javax.swing.JFrame {
    
    private Encoder enc;
    private JFileChooser chooser;
    
    /** Creates new form MainGUI */
    public MainGUI(Encoder enc) {
        this.enc = enc;
        chooser = new JFileChooser();
        
        initComponents();
        
        updateQueue();

        int value = jAudioSlider.getValue();
        jAudioRate.setText(""+value);
        
        value = jVideoSlider.getValue();
        jVideoRate.setText(""+value);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jOutput = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jVideoSlider = new javax.swing.JSlider();
        jAudioSlider = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jVideoRate = new javax.swing.JLabel();
        jAudioRate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iso2Avi - Main");

        jScrollPane1.setViewportView(jList);

        jLabel1.setText("Queue:");

        jButton1.setText("Start Encodeing");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Inputfile:");

        jLabel3.setText("Outputfile:");

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Browse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Browse");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jVideoSlider.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jVideoSlider.setMajorTickSpacing(100);
        jVideoSlider.setMaximum(2500);
        jVideoSlider.setMinimum(500);
        jVideoSlider.setMinorTickSpacing(100);
        jVideoSlider.setPaintTicks(true);
        jVideoSlider.setSnapToTicks(true);
        jVideoSlider.setValue(1500);
        jVideoSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jVideoSliderStateChanged(evt);
            }
        });

        jAudioSlider.setMajorTickSpacing(32);
        jAudioSlider.setMaximum(256);
        jAudioSlider.setMinimum(64);
        jAudioSlider.setMinorTickSpacing(32);
        jAudioSlider.setPaintLabels(true);
        jAudioSlider.setPaintTicks(true);
        jAudioSlider.setSnapToTicks(true);
        jAudioSlider.setValue(128);
        jAudioSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jAudioSliderStateChanged(evt);
            }
        });

        jLabel4.setText("Video Bitrate:");

        jLabel5.setText("Audio Bitrate:");

        jVideoRate.setText("$VIDEO");

        jAudioRate.setText("$AUDIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addComponent(jInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jVideoRate)
                            .addComponent(jAudioRate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jAudioSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jVideoSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jVideoRate))
                    .addComponent(jVideoSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jAudioRate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jAudioSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAudioSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jAudioSliderStateChanged
        int value = jAudioSlider.getValue();
        jAudioRate.setText(""+value);
    }//GEN-LAST:event_jAudioSliderStateChanged

    private void jVideoSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jVideoSliderStateChanged
        int value = jVideoSlider.getValue();
        jVideoRate.setText(""+value);
    }//GEN-LAST:event_jVideoSliderStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Run the Queue
        
        enc.runJob();
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        EncoderOptions eo = (EncoderOptions)jList.getSelectedValue();
        enc.removeJob(eo);
        
        updateQueue();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Add item to queue
        
        String input = jInput.getText();
        String output = jOutput.getText();
        
        int video = jVideoSlider.getValue();
        int audio = jAudioSlider.getValue();
        
        EncoderOptions eo = new EncoderOptions(input, output);
        eo.setBitrate(video);
        eo.setAbitrate(audio);
        
        enc.addJob(eo);
        
        jInput.setText("");
        jOutput.setText("");
        
        updateQueue();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Browse for outputfile
        try {
            File selected = new File(jOutput.getText());
            chooser.setSelectedFile(selected);
        }
        catch(Exception e) {
            
        }
        int i = chooser.showOpenDialog(null);
        if( i == JFileChooser.APPROVE_OPTION ) {
            jOutput.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Browse for inputfile
        
        int i = chooser.showOpenDialog(null);
        if( i == JFileChooser.APPROVE_OPTION ) {
            jInput.setText(chooser.getSelectedFile().getPath());
            jOutput.setText(chooser.getSelectedFile().getPath().substring(0,chooser.getSelectedFile().getPath().length()-4)+".avi");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void updateQueue() {
        Vector data = new Vector<EncoderOptions>();
        for(EncoderOptions e : enc.getQueue()) {
            data.add(e);
        }
        
        jList.setListData(data);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAudioRate;
    private javax.swing.JSlider jAudioSlider;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JTextField jInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList;
    private javax.swing.JTextField jOutput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jVideoRate;
    private javax.swing.JSlider jVideoSlider;
    // End of variables declaration//GEN-END:variables
    
}
